// Postgres, over a small query helper rather than an ORM.
//
// The helper exists for one reason: `pg` wants numbered placeholders ($1, $2) while
// every query in this app was written with `?`. Translating in one place kept the SQL
// readable and made the port mechanical instead of a rewrite. It also gives the three
// shapes the app actually uses — one row, many rows, no rows — so call sites read as
// they did under node:sqlite, only awaited.
//
// Configure with DATABASE_URL. Coolify hands you one when you attach a Postgres.

import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import pg from 'pg';

const url = process.env.DATABASE_URL;
if (!url) throw new Error('DATABASE_URL is not set — point it at your Postgres instance');

// `pg` returns int8 and numeric as strings to protect precision it cannot know we do
// not need. Nothing here is anywhere near 2^53, so parse them and keep the app's types.
pg.types.setTypeParser(pg.types.builtins.INT8, Number);
pg.types.setTypeParser(pg.types.builtins.NUMERIC, Number);
pg.types.setTypeParser(pg.types.builtins.FLOAT8, Number);

export const pool = new pg.Pool({
	connectionString: url,
	max: Number(process.env.DATABASE_POOL ?? 10),
	// Coolify's Postgres sits on the same private network, so TLS is off unless asked.
	ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : undefined
});

pool.on('error', (e) => console.error('[db] idle client error:', e.message));

/** `?` -> `$1, $2, ...` in order. */
const numbered = (sql: string) => {
	let n = 0;
	return sql.replace(/\?/g, () => `$${++n}`);
};

export async function all<T>(sql: string, ...params: unknown[]): Promise<T[]> {
	const res = await pool.query(numbered(sql), params);
	return res.rows as T[];
}

export async function one<T>(sql: string, ...params: unknown[]): Promise<T | undefined> {
	return (await all<T>(sql, ...params))[0];
}

export async function run(sql: string, ...params: unknown[]): Promise<number> {
	const res = await pool.query(numbered(sql), params);
	return res.rowCount ?? 0;
}

/** Several statements as one unit — used by the schema and by the SQLite import. */
export async function tx<T>(fn: (c: pg.PoolClient) => Promise<T>): Promise<T> {
	const c = await pool.connect();
	try {
		await c.query('BEGIN');
		const out = await fn(c);
		await c.query('COMMIT');
		return out;
	} catch (e) {
		await c.query('ROLLBACK');
		throw e;
	} finally {
		c.release();
	}
}

/* ---------- schema ----------
   Safe to run on every boot: every statement is IF NOT EXISTS, so a fresh database and
   a running one converge on the same shape. Postgres has ADD COLUMN IF NOT EXISTS, so
   the PRAGMA-probing the SQLite version needed is gone with it. */

const SCHEMA = `
CREATE TABLE IF NOT EXISTS players (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  pass       TEXT NOT NULL,
  google_sub TEXT,
  email      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- SQLite had COLLATE NOCASE on the name; a functional unique index is the same
-- guarantee here, and it is what the sign-in lookup matches on.
CREATE UNIQUE INDEX IF NOT EXISTS players_name ON players (lower(name));
CREATE UNIQUE INDEX IF NOT EXISTS players_google ON players (google_sub) WHERE google_sub IS NOT NULL;

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  player_id  INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS games (
  id          TEXT PRIMARY KEY,
  season      INTEGER NOT NULL,
  week        INTEGER NOT NULL,
  start       TIMESTAMPTZ NOT NULL,
  state       TEXT NOT NULL,          -- pre | in | post
  detail      TEXT,
  home_abbr   TEXT, home_name TEXT, home_logo TEXT, home_rank INTEGER, home_score INTEGER,
  away_abbr   TEXT, away_name TEXT, away_logo TEXT, away_rank INTEGER, away_score INTEGER,
  home_conf   INTEGER, away_conf INTEGER,
  home_color  TEXT, away_color TEXT,
  home_alt_color TEXT, away_alt_color TEXT,
  spread      DOUBLE PRECISION, ml_home INTEGER, ml_away INTEGER, over_under DOUBLE PRECISION,
  venue       TEXT, tv TEXT,
  odds_frozen BOOLEAN NOT NULL DEFAULT false,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS games_week ON games (season, week, start);

-- Colour read out of a team's logo, for the schools ESPN files as flat #000000.
-- Keyed by logo URL because that is the only stable team identifier we store.
CREATE TABLE IF NOT EXISTS logo_colors (
  logo       TEXT PRIMARY KEY,
  color      TEXT,                    -- null = logo really is monochrome; don't refetch
  bg         TEXT,                    -- background the two flags below were measured against
  halo_on    BOOLEAN NOT NULL DEFAULT false,  -- logo needs an outline on the picked colour
  halo_off   BOOLEAN NOT NULL DEFAULT false,  -- ...and on the unpicked tint
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS watches (
  player_id  INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  team       TEXT NOT NULL,
  PRIMARY KEY (player_id, team)
);

-- The frozen Games of the Week board. Computed once and never recomputed: lines move
-- all week, and a slate that reshuffled under a board someone had already filled in
-- would orphan their picks.
CREATE TABLE IF NOT EXISTS slate (
  season    INTEGER NOT NULL,
  week      INTEGER NOT NULL,
  game_id   TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  seed      INTEGER NOT NULL,        -- 1 = the best game of the week
  frozen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (season, week, game_id)
);

-- These live in their own table because they obey different rules: one per game, no
-- kind, scored win/loss rather than on points, and worthless until the whole board is
-- submitted.
CREATE TABLE IF NOT EXISTS slate_picks (
  player_id  INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  game_id    TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  side       TEXT NOT NULL CHECK (side IN ('home','away')),
  odds_at    INTEGER,                -- how it was priced at pick time; a record, not a score
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (player_id, game_id)
);

-- All or nothing. Until this row exists the picks are a draft, and a draft counts for
-- nothing however good it looks.
CREATE TABLE IF NOT EXISTS slate_submits (
  player_id    INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  season       INTEGER NOT NULL,
  week         INTEGER NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (player_id, season, week)
);

CREATE TABLE IF NOT EXISTS picks (
  player_id  INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  game_id    TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  kind       TEXT NOT NULL CHECK (kind IN ('spread','ml')),
  side       TEXT NOT NULL CHECK (side IN ('home','away')),
  spread_at  DOUBLE PRECISION,       -- line locked in at pick time
  odds_at    INTEGER,                -- price locked in at pick time
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (player_id, game_id, kind)
);
`;

let ready: Promise<void> | null = null;

/** Bring the schema up. Awaited once per process, before the first query runs. */
export function migrate(): Promise<void> {
	ready ??= pool.query(SCHEMA).then(() => void console.log('[db] schema ready'));
	return ready;
}

/* ---------- auth (scrypt + opaque session tokens; both stdlib) ---------- */

export function hashPass(pass: string): string {
	const salt = randomBytes(16);
	return `${salt.toString('hex')}:${scryptSync(pass, salt, 64).toString('hex')}`;
}

export function verifyPass(pass: string, stored: string): boolean {
	const [saltHex, keyHex] = stored.split(':');
	if (!saltHex || !keyHex) return false;
	const key = Buffer.from(keyHex, 'hex');
	const test = scryptSync(pass, Buffer.from(saltHex, 'hex'), key.length);
	return timingSafeEqual(key, test);
}

export async function createSession(playerId: number): Promise<string> {
	const token = randomBytes(32).toString('base64url');
	await run('INSERT INTO sessions (token, player_id) VALUES (?, ?)', token, playerId);
	return token;
}

export async function playerForToken(token: string | undefined) {
	if (!token) return null;
	return (
		(await one<{ id: number; name: string }>(
			'SELECT p.id, p.name FROM sessions s JOIN players p ON p.id = s.player_id WHERE s.token = ?',
			token
		)) ?? null
	);
}

export const dropSession = (token: string) => run('DELETE FROM sessions WHERE token = ?', token);
